server:
  port: 8082
  context-path: /motorzz

params:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/motorzz?zeroDateTimeBehavior=convertToNull&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    connectionTimeout: 600000
    username: root
    password: root
#    password: pastrav97
    maximumPoolSize: 15
    initialize: true

spring.datasource.separator: ^;
spring.http.multipart.max-file-size: 20MB

management:
  security:
    enabled: false

security:
  basic:
    enabled: false

spring:
  jmx:
    enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: fmarketapp@gmail.com
    password: FmarketApp123
    properties.mail.smtp:
      socketFactory.port: 465
      socketFactory.class: javax.net.ssl.SSLSocketFactory
      socketFactory.fallback: false
      auth: true
      ssl.enable: true
      starttls.enable: true
  jackson:
    date-format: yyyy-MM-dd
spring.thymeleaf.cache: false

properties:
  baseUrl: http://motorzz.ro/
  registrationTokenDurationInHours: 8
  authenticationTokenDurationInHours: 8